//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuiteAdmin.ReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportContract", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class ReportContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FuiteAdmin.ReportService.State StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FuiteAdmin.ReportService.State State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    public enum State : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Affected = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.ResultReports))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.ResultChanges))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.ResultIp))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultReports", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class ResultReports : FuiteAdmin.ReportService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FuiteAdmin.ReportService.ReportContract[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FuiteAdmin.ReportService.ReportContract[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultChanges", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class ResultChanges : FuiteAdmin.ReportService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FuiteAdmin.ReportService.Change[] DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FuiteAdmin.ReportService.Change[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultIp", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class ResultIp : FuiteAdmin.ReportService.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Change", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class Change : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FuiteAdmin.ReportService.User OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> Operator_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Report_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FuiteAdmin.ReportService.User Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Operator_id {
            get {
                return this.Operator_idField;
            }
            set {
                if ((this.Operator_idField.Equals(value) != true)) {
                    this.Operator_idField = value;
                    this.RaisePropertyChanged("Operator_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Report_id {
            get {
                return this.Report_idField;
            }
            set {
                if ((this.Report_idField.Equals(value) != true)) {
                    this.Report_idField = value;
                    this.RaisePropertyChanged("Report_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI.WebSrvPortal.Auth")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.ComponentModel.PropertyChangedEventHandler PropertyChanged1Field;
        
        private string idAgenceFieldField;
        
        private string idServiceFieldField;
        
        private System.Guid idUserFieldField;
        
        private string loginFieldField;
        
        private string loginMaximoFieldField;
        
        private string mailFieldField;
        
        private string matriculeFieldField;
        
        private string nomCompletFieldField;
        
        private string ticketAuthFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="PropertyChanged", IsRequired=true)]
        public System.ComponentModel.PropertyChangedEventHandler PropertyChanged1 {
            get {
                return this.PropertyChanged1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyChanged1Field, value) != true)) {
                    this.PropertyChanged1Field = value;
                    this.RaisePropertyChanged("PropertyChanged1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idAgenceField {
            get {
                return this.idAgenceFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.idAgenceFieldField, value) != true)) {
                    this.idAgenceFieldField = value;
                    this.RaisePropertyChanged("idAgenceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string idServiceField {
            get {
                return this.idServiceFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.idServiceFieldField, value) != true)) {
                    this.idServiceFieldField = value;
                    this.RaisePropertyChanged("idServiceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid idUserField {
            get {
                return this.idUserFieldField;
            }
            set {
                if ((this.idUserFieldField.Equals(value) != true)) {
                    this.idUserFieldField = value;
                    this.RaisePropertyChanged("idUserField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string loginField {
            get {
                return this.loginFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.loginFieldField, value) != true)) {
                    this.loginFieldField = value;
                    this.RaisePropertyChanged("loginField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string loginMaximoField {
            get {
                return this.loginMaximoFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.loginMaximoFieldField, value) != true)) {
                    this.loginMaximoFieldField = value;
                    this.RaisePropertyChanged("loginMaximoField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mailField {
            get {
                return this.mailFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.mailFieldField, value) != true)) {
                    this.mailFieldField = value;
                    this.RaisePropertyChanged("mailField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string matriculeField {
            get {
                return this.matriculeFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.matriculeFieldField, value) != true)) {
                    this.matriculeFieldField = value;
                    this.RaisePropertyChanged("matriculeField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nomCompletField {
            get {
                return this.nomCompletFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nomCompletFieldField, value) != true)) {
                    this.nomCompletFieldField = value;
                    this.RaisePropertyChanged("nomCompletField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ticketAuthField {
            get {
                return this.ticketAuthFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ticketAuthFieldField, value) != true)) {
                    this.ticketAuthFieldField = value;
                    this.RaisePropertyChanged("ticketAuthField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.GetReportsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.GetChangesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.GetReportRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.BanIpRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FuiteAdmin.ReportService.SetReportRequest))]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ticketField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                if ((object.ReferenceEquals(this.ticketField, value) != true)) {
                    this.ticketField = value;
                    this.RaisePropertyChanged("ticket");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReportsRequest", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class GetReportsRequest : FuiteAdmin.ReportService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maxIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int minIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FuiteAdmin.ReportService.State stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxIndex {
            get {
                return this.maxIndexField;
            }
            set {
                if ((this.maxIndexField.Equals(value) != true)) {
                    this.maxIndexField = value;
                    this.RaisePropertyChanged("maxIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minIndex {
            get {
                return this.minIndexField;
            }
            set {
                if ((this.minIndexField.Equals(value) != true)) {
                    this.minIndexField = value;
                    this.RaisePropertyChanged("minIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FuiteAdmin.ReportService.State state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetChangesRequest", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class GetChangesRequest : FuiteAdmin.ReportService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int reportIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reportId {
            get {
                return this.reportIdField;
            }
            set {
                if ((this.reportIdField.Equals(value) != true)) {
                    this.reportIdField = value;
                    this.RaisePropertyChanged("reportId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReportRequest", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class GetReportRequest : FuiteAdmin.ReportService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BanIpRequest", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class BanIpRequest : FuiteAdmin.ReportService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetReportRequest", Namespace="http://schemas.datacontract.org/2004/07/FuiteAPI")]
    [System.SerializableAttribute()]
    public partial class SetReportRequest : FuiteAdmin.ReportService.Request {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FuiteAdmin.ReportService.ReportContract reportField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FuiteAdmin.ReportService.ReportContract report {
            get {
                return this.reportField;
            }
            set {
                if ((object.ReferenceEquals(this.reportField, value) != true)) {
                    this.reportField = value;
                    this.RaisePropertyChanged("report");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/AddReport", ReplyAction="http://tempuri.org/IReportService/AddReportResponse")]
        FuiteAdmin.ReportService.Result AddReport(FuiteAdmin.ReportService.ReportContract report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/AddReport", ReplyAction="http://tempuri.org/IReportService/AddReportResponse")]
        System.Threading.Tasks.Task<FuiteAdmin.ReportService.Result> AddReportAsync(FuiteAdmin.ReportService.ReportContract report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/SetReport", ReplyAction="http://tempuri.org/IReportService/SetReportResponse")]
        FuiteAdmin.ReportService.Result SetReport(FuiteAdmin.ReportService.SetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/SetReport", ReplyAction="http://tempuri.org/IReportService/SetReportResponse")]
        System.Threading.Tasks.Task<FuiteAdmin.ReportService.Result> SetReportAsync(FuiteAdmin.ReportService.SetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetReports", ReplyAction="http://tempuri.org/IReportService/GetReportsResponse")]
        FuiteAdmin.ReportService.ResultReports GetReports(FuiteAdmin.ReportService.GetReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetReports", ReplyAction="http://tempuri.org/IReportService/GetReportsResponse")]
        System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultReports> GetReportsAsync(FuiteAdmin.ReportService.GetReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetChanges", ReplyAction="http://tempuri.org/IReportService/GetChangesResponse")]
        FuiteAdmin.ReportService.ResultChanges GetChanges(FuiteAdmin.ReportService.GetChangesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetChanges", ReplyAction="http://tempuri.org/IReportService/GetChangesResponse")]
        System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultChanges> GetChangesAsync(FuiteAdmin.ReportService.GetChangesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetReport", ReplyAction="http://tempuri.org/IReportService/GetReportResponse")]
        FuiteAdmin.ReportService.ResultReports GetReport(FuiteAdmin.ReportService.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetReport", ReplyAction="http://tempuri.org/IReportService/GetReportResponse")]
        System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultReports> GetReportAsync(FuiteAdmin.ReportService.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/SetBanIp", ReplyAction="http://tempuri.org/IReportService/SetBanIpResponse")]
        FuiteAdmin.ReportService.Result SetBanIp(FuiteAdmin.ReportService.BanIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/SetBanIp", ReplyAction="http://tempuri.org/IReportService/SetBanIpResponse")]
        System.Threading.Tasks.Task<FuiteAdmin.ReportService.Result> SetBanIpAsync(FuiteAdmin.ReportService.BanIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/IsIpBan", ReplyAction="http://tempuri.org/IReportService/IsIpBanResponse")]
        FuiteAdmin.ReportService.ResultIp IsIpBan(FuiteAdmin.ReportService.BanIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/IsIpBan", ReplyAction="http://tempuri.org/IReportService/IsIpBanResponse")]
        System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultIp> IsIpBanAsync(FuiteAdmin.ReportService.BanIpRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : FuiteAdmin.ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<FuiteAdmin.ReportService.IReportService>, FuiteAdmin.ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FuiteAdmin.ReportService.Result AddReport(FuiteAdmin.ReportService.ReportContract report) {
            return base.Channel.AddReport(report);
        }
        
        public System.Threading.Tasks.Task<FuiteAdmin.ReportService.Result> AddReportAsync(FuiteAdmin.ReportService.ReportContract report) {
            return base.Channel.AddReportAsync(report);
        }
        
        public FuiteAdmin.ReportService.Result SetReport(FuiteAdmin.ReportService.SetReportRequest request) {
            return base.Channel.SetReport(request);
        }
        
        public System.Threading.Tasks.Task<FuiteAdmin.ReportService.Result> SetReportAsync(FuiteAdmin.ReportService.SetReportRequest request) {
            return base.Channel.SetReportAsync(request);
        }
        
        public FuiteAdmin.ReportService.ResultReports GetReports(FuiteAdmin.ReportService.GetReportsRequest request) {
            return base.Channel.GetReports(request);
        }
        
        public System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultReports> GetReportsAsync(FuiteAdmin.ReportService.GetReportsRequest request) {
            return base.Channel.GetReportsAsync(request);
        }
        
        public FuiteAdmin.ReportService.ResultChanges GetChanges(FuiteAdmin.ReportService.GetChangesRequest request) {
            return base.Channel.GetChanges(request);
        }
        
        public System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultChanges> GetChangesAsync(FuiteAdmin.ReportService.GetChangesRequest request) {
            return base.Channel.GetChangesAsync(request);
        }
        
        public FuiteAdmin.ReportService.ResultReports GetReport(FuiteAdmin.ReportService.GetReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultReports> GetReportAsync(FuiteAdmin.ReportService.GetReportRequest request) {
            return base.Channel.GetReportAsync(request);
        }
        
        public FuiteAdmin.ReportService.Result SetBanIp(FuiteAdmin.ReportService.BanIpRequest request) {
            return base.Channel.SetBanIp(request);
        }
        
        public System.Threading.Tasks.Task<FuiteAdmin.ReportService.Result> SetBanIpAsync(FuiteAdmin.ReportService.BanIpRequest request) {
            return base.Channel.SetBanIpAsync(request);
        }
        
        public FuiteAdmin.ReportService.ResultIp IsIpBan(FuiteAdmin.ReportService.BanIpRequest request) {
            return base.Channel.IsIpBan(request);
        }
        
        public System.Threading.Tasks.Task<FuiteAdmin.ReportService.ResultIp> IsIpBanAsync(FuiteAdmin.ReportService.BanIpRequest request) {
            return base.Channel.IsIpBanAsync(request);
        }
    }
}
