//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuiteAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public string description { get; set; }
        public string picture { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public string ip { get; set; }
        public int id { get; set; }
        public int state { get; set; }
    }
}
