//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuiteAPI.WebSrvPortal.Auth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.17.100.182/portal/webservices/", ConfigurationName="WebSrvPortal.Auth.AuthServiceSoap")]
    public interface AuthServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenirTicket(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ObtenirTicketAsync(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirDroitSurApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.Droits ObtenirDroitSurApplication(string strTicket, string strTypeApplication, string strApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirDroitSurApplication", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.Droits> ObtenirDroitSurApplicationAsync(string strTicket, string strTypeApplication, string strApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirDroitSurApplicationAvecLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.Droits ObtenirDroitSurApplicationAvecLogin(string strUser, string strPassword, string strTypeApplication, string strApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirDroitSurApplicationAvecLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.Droits> ObtenirDroitSurApplicationAvecLoginAsync(string strUser, string strPassword, string strTypeApplication, string strApplication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateur", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateur(string strTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateur", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurAsync(string strTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurAvecLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurAvecLogin(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurAvecLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurAvecLoginAsync(string strUser, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurSurGID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurSurGID(string GID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurSurGID", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurSurGIDAsync(string GID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurSurIdentifiant", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurSurIdentifiant(System.Guid guidIdUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurSurIdentifiant", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurSurIdentifiantAsync(System.Guid guidIdUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurSurMatricule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurSurMatricule(string strMatricule);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirUtilisateurSurMatricule", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurSurMatriculeAsync(string strMatricule);
        
        // CODEGEN : Le paramètre 'ObtenirAppartenancesEntreeAnnuaireResult' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirAppartenancesEntreeAnnuaire", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireResponse ObtenirAppartenancesEntreeAnnuaire(FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.17.100.182/portal/webservices/ObtenirAppartenancesEntreeAnnuaire", ReplyAction="*")]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireResponse> ObtenirAppartenancesEntreeAnnuaireAsync(FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.17.100.182/portal/webservices/")]
    public enum Droits {
        
        /// <remarks/>
        Aucun,
        
        /// <remarks/>
        Lecture,
        
        /// <remarks/>
        Proprietaire,
        
        /// <remarks/>
        Ecriture,
        
        /// <remarks/>
        Approbateur,
        
        /// <remarks/>
        Concepteur,
        
        /// <remarks/>
        Admin,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.17.100.182/portal/webservices/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idUserField;
        
        private string matriculeField;
        
        private string nomCompletField;
        
        private string loginField;
        
        private string loginMaximoField;
        
        private string mailField;
        
        private string idServiceField;
        
        private string idAgenceField;
        
        private string ticketAuthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
                this.RaisePropertyChanged("IdUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Matricule {
            get {
                return this.matriculeField;
            }
            set {
                this.matriculeField = value;
                this.RaisePropertyChanged("Matricule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NomComplet {
            get {
                return this.nomCompletField;
            }
            set {
                this.nomCompletField = value;
                this.RaisePropertyChanged("NomComplet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LoginMaximo {
            get {
                return this.loginMaximoField;
            }
            set {
                this.loginMaximoField = value;
                this.RaisePropertyChanged("LoginMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("Mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IdService {
            get {
                return this.idServiceField;
            }
            set {
                this.idServiceField = value;
                this.RaisePropertyChanged("IdService");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IdAgence {
            get {
                return this.idAgenceField;
            }
            set {
                this.idAgenceField = value;
                this.RaisePropertyChanged("IdAgence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TicketAuth {
            get {
                return this.ticketAuthField;
            }
            set {
                this.ticketAuthField = value;
                this.RaisePropertyChanged("TicketAuth");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.17.100.182/portal/webservices/")]
    public partial class ElementAnnuaire : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idAnnuaireField;
        
        private string nomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Guid IdAnnuaire {
            get {
                return this.idAnnuaireField;
            }
            set {
                this.idAnnuaireField = value;
                this.RaisePropertyChanged("IdAnnuaire");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
                this.RaisePropertyChanged("Nom");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenirAppartenancesEntreeAnnuaire", WrapperNamespace="http://10.17.100.182/portal/webservices/", IsWrapped=true)]
    public partial class ObtenirAppartenancesEntreeAnnuaireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.17.100.182/portal/webservices/", Order=0)]
        public System.Guid guidIdAnnuaire;
        
        public ObtenirAppartenancesEntreeAnnuaireRequest() {
        }
        
        public ObtenirAppartenancesEntreeAnnuaireRequest(System.Guid guidIdAnnuaire) {
            this.guidIdAnnuaire = guidIdAnnuaire;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenirAppartenancesEntreeAnnuaireResponse", WrapperNamespace="http://10.17.100.182/portal/webservices/", IsWrapped=true)]
    public partial class ObtenirAppartenancesEntreeAnnuaireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://10.17.100.182/portal/webservices/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Elements", IsNullable=false)]
        public FuiteAPI.WebSrvPortal.Auth.ElementAnnuaire[] ObtenirAppartenancesEntreeAnnuaireResult;
        
        public ObtenirAppartenancesEntreeAnnuaireResponse() {
        }
        
        public ObtenirAppartenancesEntreeAnnuaireResponse(FuiteAPI.WebSrvPortal.Auth.ElementAnnuaire[] ObtenirAppartenancesEntreeAnnuaireResult) {
            this.ObtenirAppartenancesEntreeAnnuaireResult = ObtenirAppartenancesEntreeAnnuaireResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthServiceSoapChannel : FuiteAPI.WebSrvPortal.Auth.AuthServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceSoapClient : System.ServiceModel.ClientBase<FuiteAPI.WebSrvPortal.Auth.AuthServiceSoap>, FuiteAPI.WebSrvPortal.Auth.AuthServiceSoap {
        
        public AuthServiceSoapClient() {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObtenirTicket(string strUser, string strPassword) {
            return base.Channel.ObtenirTicket(strUser, strPassword);
        }
        
        public System.Threading.Tasks.Task<string> ObtenirTicketAsync(string strUser, string strPassword) {
            return base.Channel.ObtenirTicketAsync(strUser, strPassword);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.Droits ObtenirDroitSurApplication(string strTicket, string strTypeApplication, string strApplication) {
            return base.Channel.ObtenirDroitSurApplication(strTicket, strTypeApplication, strApplication);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.Droits> ObtenirDroitSurApplicationAsync(string strTicket, string strTypeApplication, string strApplication) {
            return base.Channel.ObtenirDroitSurApplicationAsync(strTicket, strTypeApplication, strApplication);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.Droits ObtenirDroitSurApplicationAvecLogin(string strUser, string strPassword, string strTypeApplication, string strApplication) {
            return base.Channel.ObtenirDroitSurApplicationAvecLogin(strUser, strPassword, strTypeApplication, strApplication);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.Droits> ObtenirDroitSurApplicationAvecLoginAsync(string strUser, string strPassword, string strTypeApplication, string strApplication) {
            return base.Channel.ObtenirDroitSurApplicationAvecLoginAsync(strUser, strPassword, strTypeApplication, strApplication);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateur(string strTicket) {
            return base.Channel.ObtenirUtilisateur(strTicket);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurAsync(string strTicket) {
            return base.Channel.ObtenirUtilisateurAsync(strTicket);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurAvecLogin(string strUser, string strPassword) {
            return base.Channel.ObtenirUtilisateurAvecLogin(strUser, strPassword);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurAvecLoginAsync(string strUser, string strPassword) {
            return base.Channel.ObtenirUtilisateurAvecLoginAsync(strUser, strPassword);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurSurGID(string GID) {
            return base.Channel.ObtenirUtilisateurSurGID(GID);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurSurGIDAsync(string GID) {
            return base.Channel.ObtenirUtilisateurSurGIDAsync(GID);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurSurIdentifiant(System.Guid guidIdUser) {
            return base.Channel.ObtenirUtilisateurSurIdentifiant(guidIdUser);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurSurIdentifiantAsync(System.Guid guidIdUser) {
            return base.Channel.ObtenirUtilisateurSurIdentifiantAsync(guidIdUser);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.User ObtenirUtilisateurSurMatricule(string strMatricule) {
            return base.Channel.ObtenirUtilisateurSurMatricule(strMatricule);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.User> ObtenirUtilisateurSurMatriculeAsync(string strMatricule) {
            return base.Channel.ObtenirUtilisateurSurMatriculeAsync(strMatricule);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireResponse FuiteAPI.WebSrvPortal.Auth.AuthServiceSoap.ObtenirAppartenancesEntreeAnnuaire(FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest request) {
            return base.Channel.ObtenirAppartenancesEntreeAnnuaire(request);
        }
        
        public FuiteAPI.WebSrvPortal.Auth.ElementAnnuaire[] ObtenirAppartenancesEntreeAnnuaire(System.Guid guidIdAnnuaire) {
            FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest inValue = new FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest();
            inValue.guidIdAnnuaire = guidIdAnnuaire;
            FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireResponse retVal = ((FuiteAPI.WebSrvPortal.Auth.AuthServiceSoap)(this)).ObtenirAppartenancesEntreeAnnuaire(inValue);
            return retVal.ObtenirAppartenancesEntreeAnnuaireResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireResponse> FuiteAPI.WebSrvPortal.Auth.AuthServiceSoap.ObtenirAppartenancesEntreeAnnuaireAsync(FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest request) {
            return base.Channel.ObtenirAppartenancesEntreeAnnuaireAsync(request);
        }
        
        public System.Threading.Tasks.Task<FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireResponse> ObtenirAppartenancesEntreeAnnuaireAsync(System.Guid guidIdAnnuaire) {
            FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest inValue = new FuiteAPI.WebSrvPortal.Auth.ObtenirAppartenancesEntreeAnnuaireRequest();
            inValue.guidIdAnnuaire = guidIdAnnuaire;
            return ((FuiteAPI.WebSrvPortal.Auth.AuthServiceSoap)(this)).ObtenirAppartenancesEntreeAnnuaireAsync(inValue);
        }
    }
}
